### ISSUE TITLE
it turns off securly and goguardian but not ckauth \:

### ISSUE THREAD

**Issue by rockisdirt** [dragon731012/cauDNS#12]
its still great because killcurly and insecurly stoped working and my friend could not go on to many game websites and unblockers. but now thanks to cauDNS me and my best friend can play games and unblockers, and also it disabled goguardian so now the teachers can't close are tabs or monitor them. (btw if GoGuardian didn't turn off, go to manage extension and flip the allow to URL files a couple of times then check

**Comment by MyUsernameIsDis** [comment]
is there a way to turn goguardian back on?

**Comment by dragon731012** [comment]
Yes, just upload the revive.onc file
