### ISSUE TITLE
Am I doing it right?

### ISSUE THREAD

**Issue by Gpar2023** [dragon731012/cauDNS#15]
** I USE CKauthenticator! **

First i go to the data:text/html , follow the "instructions" and chrome://network#state works, I paste what looks like to be json code into the "input" and press download but download does nothing at all. How much a press it nothing happens. Could ANYBODY help? :(

**Comment by dragon731012** [comment]
Make sure you do not miss any curly braces. ({})

**Comment by dragon731012** [comment]
Or try the web version. I can host one for you if you want.

**Comment by Gpar2023** [comment]
THANKS! *It works* :D :D

**Comment by dragon731012** [comment]
np
