### ISSUE TITLE
Nothing loading 

### ISSUE THREAD

**Issue by thascxz** [dragon731012/cauDNS#8]
Nothing loads after I import kill.onc like losing signal connection but when I revive it its back to normal.

**Comment by dragon731012** [comment]
Are you using an updated version of cauDNS?

**Comment by eeeqr** [comment]
It don't work at school

**Comment by Sparklingpeackock67612** [comment]
nothing happens after I import the file
![image](https://github.com/dragon731012/cauDNS/assets/151665987/c2df9d6e-207f-4792-a055-9d5a2366b6a0)

**Comment by Sparklingpeackock67612** [comment]
it just says there was one network imported
what do I do after that?

**Comment by dragon731012** [comment]
Ur done

**Comment by dragon731012** [comment]
> It don't work at school

Set it up for ur school network too
